### ISSUE TITLE
Deploy new CTS app to production

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#592]
Once the app is ready, prepare for deployment.

```[tasklist]
### Tasks
- [x] Configure Azure App for authentication
- [x] Create Web Deploy publish profile
- [x] Create server-specific settings and config files
- [x] Add `FixUserId` UDF to database
- [x] Delete "Dev" testing pages
- [ ] #800
- [x] Update maintenance page scripts
- [x] Enable app maintenance page for CTS
- [x] Configure IIS on server
- [x] Bump version number
- [x] Deploy app to server
- [x] Apply data migration scripts
- [x] Remove app maintenance page
- [x] Test
```
