### ISSUE TITLE
Prepare for QA

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#723]
Deploy to dev server to test the migration process and prepare for QA.

```[tasklist]
### Tasks
- [x] Configure Azure App for authentication.
- [x] Create Web Deploy publish profile.
- [x] Create server-specific settings and config files.
- [x] Configure IIS on server.
- [x] Deploy app to server.
```

**Comment by dougwaldron** [comment]
Dev server is ready for functionality QA.
