### ISSUE TITLE
Prepare for UAT

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#724]
Deploy to the test server and prepare for UAT.

```[tasklist]
### Tasks
- [x] Configure Azure App for authentication.
- [x] Create Web Deploy publish profile.
- [ ] https://github.com/gaepdit/complaint-tracking/issues/767
- [x] Create server-specific settings and config files.
- [x] Add `FixUserId` UDF to database
- [x] Configure IIS on server.
- [x] Deploy app to server.
- [x] Apply data migration scripts.
- [x] Set up temporary resource mailbox for notifications during UAT
- [x] Write a UAT introduction email
```

**Comment by dougwaldron** [comment]
Emailed Jim that CTS is ready for UAT
